# Generated by Django 6.0.4 on 2026-05-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='rota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rotas.rota'),
        ),
    ]
