# Generated by Django 6.0.5 on 2026-05-07 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_userdjango'),
        ('core', '0002_alter_perfil_filial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
            ],
        ),
    ]
