# Generated by Django 6.0.5 on 2026-05-07 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filialcliente'),
        ('diario', '0001_initial'),
        ('fornecedores', '0002_alter_fornecedor_email'),
        ('motoristas', '0002_alter_motorista_email'),
        ('rotas', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilialDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.diario')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
            ],
        ),
        migrations.CreateModel(
            name='FilialFornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('fornecedor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedores.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='FilialMotoristas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('motoristas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motoristas.motorista')),
            ],
        ),
        migrations.CreateModel(
            name='FilialRotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('rotas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rotas.rota')),
            ],
        ),
        migrations.CreateModel(
            name='FilialVeiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial')),
                ('veiculos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
    ]
