# Generated by Django 6.0.5 on 2026-05-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_filialdiario_filialfornecedores_filialmotoristas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filialmotoristas',
            old_name='motoristas',
            new_name='motorista',
        ),
    ]
