# Generated by Django 6.0.5 on 2026-05-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_motoristas_filialmotoristas_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filialcliente',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AlterField(
            model_name='filialdiario',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AlterField(
            model_name='filialfornecedores',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AlterField(
            model_name='filialmotoristas',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AlterField(
            model_name='filialrotas',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
        migrations.AlterField(
            model_name='filialveiculos',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.filial'),
        ),
    ]
