# Generated by Django 6.0.2 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_filialcliente_filial_alter_filialdiario_filial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
