# Generated by Django 6.0.5 on 2026-05-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo_servico', models.CharField(choices=[('manutencao', 'Manutenção'), ('combustivel', 'Combustível'), ('pecas', 'Peças')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
