# Generated by Django 6.0.4 on 2026-05-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
