# Generated by Django 6.0.4 on 2026-05-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_fornecedor_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_servico',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('combustivel', 'Combustível'), ('pecas', 'Peças')], default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
