# Generated by Django 6.0.2 on 2026-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_alter_fornecedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
