# Generated by Django 6.0.4 on 2026-05-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_remove_fornecedor_empresa_remove_fornecedor_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='empresa',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(default=45, max_length=200),
            preserve_default=False,
        ),
    ]
