# Generated by Django 6.0.5 on 2026-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_fornecedor_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
