# Generated by Django 6.0.5 on 2026-05-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10)),
                ('cor', models.CharField(default='Desconhecida', max_length=50)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motoristas.motorista')),
            ],
        ),
    ]
