# Generated by Django 6.0.4 on 2026-05-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='Desconhecida', max_length=50),
        ),
    ]
