# Generated by Django 6.0.5 on 2026-05-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='userDjango',
        ),
    ]
