# Generated by Django 6.0.5 on 2026-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnh',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
