# Generated by Django 6.0.4 on 2026-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
