# Generated by Django 6.0.5 on 2026-05-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
