# Generated by Django 6.0.2 on 2026-05-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0003_alter_motorista_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cnh',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
