# Generated by Django 6.0.5 on 2026-05-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoristas', '0005_motorista_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
