# Generated by Django 6.0.4 on 2026-05-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20),
        ),
    ]
